chars:
  regular:
    space: ' '
    disc: 'o'
    vert_divider: '|'
    horiz_divider: '-'

  fancy:
    space: ' '
    disc: '🎾'
    vert_divider: '🔺'
    horiz_divider: '🔻'

digits:
  '0':
    - [1, 1, 1]
    - [1, 0, 1]
    - [1, 1, 1]

  '1':
    - [0, 1, 0]
    - [0, 1, 0]
    - [0, 1, 0]

  '2':
    - [1, 1, 0]
    - [0, 1, 0]
    - [0, 1, 1]

animation:
  tween-scale: 0.1
